name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 设置触发分支
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '18'  # 设置Node.js版本

    - name: Install dependencies
      run: npm install  # 安装依赖，根据项目类型可能需要调整命令（如yarn install）

    - name: Build project
      run: npm run build  # 构建命令，根据项目类型可能需要调整（如npm run build或yarn build）

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # 构建后的文件夹路径，根据项目类型可能需要调整（如dist, public等）
        cname: nav.52zhoujia.cn  # 可选，如果你需要自定义域名的话
